server:
  port: 8081

spring:
  profiles:
    active: local
  jpa:
    open-in-view: false
  hibernate:
    format_sql: true
  properties:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
springdoc:
  api-docs:
    path: /v3/api-docs  # Correct path for OpenAPI docs
  swagger-ui:
    path: /swagger-ui/  # Correct path for Swagger UI
