CREATE TABLE Users (
   Id BIGINT AUTO_INCREMENT PRIMARY KEY,
   Name VARCHAR(100) NOT NULL,
   Email VARCHAR(100) NOT NULL UNIQUE,
   Password VARCHAR(50) NOT NULL,
   Role VARCHAR(10) NOT NULL DEFAULT 'user',
   IsActive BOOLEAN DEFAULT TRUE,
   CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
