CREATE TABLE Products (
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    CategoryId BIGINT NOT NULL,
    Name VARCHAR(100) NOT NULL,
    Description TEXT NOT NULL,
    Price DECIMAL(10, 2) NOT NULL,
    Stock INTEGER NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (CategoryId) REFERENCES Categories(Id) ON DELETE CASCADE
);