CREATE TABLE Categories (
    Id UUID DEFAULT UUID() PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
